version: '3'

tasks:
  install:
    cmds:
      - npm i -g prettier
      - npm i --force

  drizzle-pull:
    cmds:
      - npx drizzle-kit pull --config drizzle/config.ts

  drizzle-push:
    cmds:
      - npx drizzle-kit push --config drizzle/config.ts

  lint:
    cmds:
      - prettier --write .

  nextlint:
    cmds:
      - npx next lint

  dev:
    cmds:
      #- npx next dev --turbopack --port 4000
      - npx tsx ./src/index.ts

  build:
    cmds:
      - npx next build
      - npx pkgroll --tsconfig tsconfig.server.json
