version: '3'

tasks:
  install:
    cmds:
      - npm i -g prettier
      - npm i

  drizzle:
    cmds:
      - bunx drizzle-kit pull --config db/drizzle.config.ts

  lint:
    cmds:
      - prettier --write .

  nextlint:
    cmds:
      - npx next lint

  dev:
    cmds:
      - npx next dev --turbopack --port 4000

  build:
    cmds:
      - npx next build
